id: ABDDBEBB4
base_file: f99F0.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:15:24.233741
  last_modified_at: 2022-05-30 23:15:24.233748
